name = "telegramantispamai"
main = "worker.ts"
compatibility_date = "2024-09-23" # Use a recent date
compatibility_flags = ["nodejs_compat"]
observability.enabled = true
workers_dev = true

routes = [
  "https://telegramantispamai.debug.org.ua/*"
]

[ai]
  binding = "AI"

[observability.logs]
  enabled = true

[vars]
  TELEGRAM_BOT_TOKEN = ""
  MY_TG_ID = "314044882"
  GROQ_API_KEY = ""
  AI_MODEL = "meta-llama/llama-4-scout-17b-16e-instruct"

[[kv_namespaces]]
  binding = "SPAM_KEYWORDS"
  id = "8610434c40e448c5aa810a24fab333fc"

[[kv_namespaces]]
  binding = "SPAM_MSGS"
  id = "6a4045d7cde44272a4305756bd6eb223"

[[kv_namespaces]]
  binding = "IMAGE_CACHE"
  id = "69f32efd369e4b6cb8225a3a49437dc5"

[[d1_databases]]
  binding = "DB"
  database_name = "tg_antispam_db"
  database_id = "13f3a442-4e62-4d91-b6b1-9bd48b9f95f8"
